### ISSUE TITLE
Update fails if repo is archived

### ISSUE THREAD

**Issue by brian-mcnamara** [salesforce/dockerfile-image-update#44]
Seeing an issue where the updater tries to update a repo even if its archived. Get the following stack
`Creating Pull Request on repo from ****/repo...
00:21:15.757 [main] [WARN] com.salesforce.dockerfileimageupdate.utils.GitHubUtil - Handling error with pull request creation...
Exception in thread "main" java.lang.NullPointerException
	at com.salesforce.dockerfileimageupdate.utils.GitHubUtil.createPullReq(GitHubUtil.java:99)
	at com.salesforce.dockerfileimageupdate.utils.DockerfileGitHubUtil.createPullReq(DockerfileGitHubUtil.java:268)
	at com.salesforce.dockerfileimageupdate.subcommands.impl.Parent.changeDockerfiles(Parent.java:206)
	at com.salesforce.dockerfileimageupdate.subcommands.impl.Parent.execute(Parent.java:64)
	at com.salesforce.dockerfileimageupdate.CommandLine.main(CommandLine.java:52)`

**Comment by brian-mcnamara** [comment]
Waiting on 1.95 of the github-api to become available. Should be an easy fix from there.
